name: COT Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 5' # Sextas às 22h

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run script
        run: python cot_update.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Resolve o erro de 'fetch first' sincronizando as mudanças
          git pull origin main --rebase
          
          git add euro_data.json
          # O '|| exit 0' evita que o robô falhe se não houver novos dados
          git commit -m "Update COT data" || exit 0
          git push origin main
